on:
  workflow_call:
    inputs:
      stage:
        description: 'stage'
        required: false
        default: beta
        type: string

env:
  IMAGE_NAME: "12ain/testcd"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clear repository
        run: |
          echo $GITHUB_WORKSPACE
          sudo rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE

      - name: Chekout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
          tags: |
            type=schedule
            type=ref,event=tag
            type=sha,prefix=,format=long,enable=true,priority=100

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: Dockerfile
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

  cd:
    runs-on: ubuntu-latest
    needs: ci
    outputs:
      stage: ${{ steps.stage.outputs.name }}
      tag: ${{ steps.stage.outputs.tag }}
    steps:
      - name: Chekout
        uses: actions/checkout@v2

      - name: setup-k8s-kustomize
        uses: grumpy-programmer/setup-k8s-kustomize@v1
        with:
          version: 4.5.4

      - id: stage
        name: Set Stage
        env:
          ref: ${{ github.ref }}
        run: |
          echo "::set-output name=name::beta"
          echo "::set-output name=tag::${{github.sha}}"
          if [[ ${ref} == refs/tags/v* ]]; then
            echo "::set-output name=name::prod"
            echo "::set-output name=tag::${ref##*/}"
          fi