name: CI

on:
  push:
    branches: 
    - main 
  workflow_dispatch:
    
env:
  sha: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Clear repository
          run: |
            pwd
            echo $GITHUB_WORKSPACE
            sudo rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE
        - id: changed_files
          name: git-changesets
          uses: collin-miller/git-changesets@v0.0.2
          with:
              # Default format is 'csv'. Other valid options are 'space-delimited' and 'json'.
              format: csv

        - name: Print steps context output
          run: |
              echo 'All=${{ steps.changed_files.outputs.all }}'
              echo 'Added=${{ steps.changed_files.outputs.added }}'
              echo 'Modified=${{ steps.changed_files.outputs.modified }}'
              echo 'Removed=${{ steps.changed_files.outputs.removed }}'
              echo 'Renamed=${{ steps.changed_files.outputs.renamed }}'
              echo 'Added/Modified=${{ steps.changed_files.outputs.added_modified }}'
  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: 
        - 14.x
        - 16.x
        - 18.x
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Script
        run: |
          npm run dev