# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
env:
  sha: ${{ github.sha }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - id: changed_files
          name: git-changesets
          uses: collin-miller/git-changesets@v0.0.2
          with:
              # Default format is 'csv'. Other valid options are 'space-delimited' and 'json'.
              format: csv

        - name: Print steps context output
          run: |
              echo 'All=${{ steps.changed_files.outputs.all }}'
              echo 'Added=${{ steps.changed_files.outputs.added }}'
              echo 'Modified=${{ steps.changed_files.outputs.modified }}'
              echo 'Removed=${{ steps.changed_files.outputs.removed }}'
              echo 'Renamed=${{ steps.changed_files.outputs.renamed }}'
              echo 'Added/Modified=${{ steps.changed_files.outputs.added_modified }}'
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Script
        run: |
          npm run dev